### ISSUE TITLE
Kuan 2020 has no reference

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#363] opened 2023-09-05 11:17 UTC
##### Description of the issue

need to check why first, can probably fix in cypher

This form is for VFB bug reports and feature requests.

If you need help, please use the [forum](https://groups.google.com/forum/#!forum/vfb-suport).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant data to help us understand your issue.

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by admclachlan** [comment] 2023-09-05 14:54
Doesn't look like this was loaded through the AddDataset notebook so I'm not sure why the ref is missing. Ref should be 'FBrf0247324'. Can this be fixed in cypher @Robbie1977 ?

**Comment by Robbie1977** [comment] 2023-09-05 15:41
@alex seems to have the ref:
```MATCH (n:DataSet {short_form:'Kuan2020'}) OPTIONAL MATCH (n)-[r]-(p:pub)```
![image](https://github.com/VirtualFlyBrain/VFB2/assets/4630768/ec4c5bc2-946e-4d80-a134-90880797ee55)

**Comment by Robbie1977** [comment] 2023-09-05 15:45
Something is wrong with the pub node as is missing at the end of pipeline pdb.ug.

**Comment by admclachlan** [comment] 2023-09-05 15:46
Yes I couldn't see it on pdb. I'm not sure how this was added. I can load it again through the notebook?

**Comment by Robbie1977** [comment] 2023-09-05 15:47
Can't see the issue is the FBrf released in FlyBase OK? As it exists in KB then it is already there!

**Closed** 2024-09-29 20:03 UTC
