### ISSUE TITLE
About Virtual Fly Brain

### ISSUE THREAD

**Issue by PREETCOIN** [VirtualFlyBrain/VFB2#381] opened 2024-09-11 14:24 UTC
### Description of the issue
WADCHAIN

This form is for VFB bug reports and feature requests.

If you need help, please use the [forum](https://groups.google.com/forum/#!forum/vfb-suport).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant data to help us understand your issue.

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

**Comment by Clare72** [comment] 2024-12-05 16:07
no issue described, possible duplicate of #382

**Closed by Clare72** 2024-12-05 16:07 UTC
