### ISSUE TITLE
GAL4 NBLAST

### ISSUE THREAD

**Issue by Clare72** [VirtualFlyBrain/VFB2#153] opened 2018-08-20 09:52 UTC
Testing NBLAST on VFB2.0 (using Fru-F-500279).
Search for similar neurons worked fine.
GAL4 search just keeps thinking (4 attempts >10 min wait) and I don't get any results.
The GAL4 search on the NBLAST site for this neuron worked (quickly).

Support info:
Referring page: https://v2.virtualflybrain.org/?i=VFB_00017894
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0 Size:[1440,723]

**Comment by Robbie1977** [comment] 2018-08-20 11:03
Can replicate and I am debugging cause:
```
 20/08/2018 10:28:00[2018-08-20 09:28:00.217] ERROR http-bio-8080-exec-10        org.apache.coyote.http11.Http11Protocol                           Error reading request, ignored java.lang.NullPointerException: null
20/08/2018 10:28:00	at uk.ac.vfb.geppetto.NBLASTQueryProcessor.process(NBLASTQueryProcessor.java:57)
20/08/2018 10:28:00	at org.geppetto.datasources.ExecuteQueryVisitor.caseProcessQuery(ExecuteQueryVisitor.java:82)
20/08/2018 10:28:00	at org.geppetto.model.datasources.util.DatasourcesSwitch.doSwitch(DatasourcesSwitch.java:106)
20/08/2018 10:28:00	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
20/08/2018 10:28:00	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
20/08/2018 10:28:00	at org.geppetto.datasources.ExecuteQueryVisitor.caseCompoundRefQuery(ExecuteQueryVisitor.java:140)
20/08/2018 10:28:00	at org.geppetto.model.datasources.util.DatasourcesSwitch.doSwitch(DatasourcesSwitch.java:136)
20/08/2018 10:28:00	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
20/08/2018 10:28:00	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
20/08/2018 10:28:00	at org.geppetto.datasources.ExecuteMultipleQueriesVisitor.caseRunnableQuery(ExecuteMultipleQueriesVisitor.java:72)
20/08/2018 10:28:00	at org.geppetto.model.datasources.util.DatasourcesSwitch.doSwitch(DatasourcesSwitch.java:153)
20/08/2018 10:28:00	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
20/08/2018 10:28:00	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
20/08/2018 10:28:00	at org.geppetto.model.util.GeppettoModelTraversal.apply(GeppettoModelTraversal.java:25)
20/08/2018 10:28:00	at org.geppetto.model.util.GeppettoModelTraversal.apply(GeppettoModelTraversal.java:72)
20/08/2018 10:28:00	at org.geppetto.datasources.ADataSourceService.getNumberOfResults(ADataSourceService.java:70)
20/08/2018 10:28:00	at org.geppetto.simulation.manager.RuntimeProject.runQueryCount(RuntimeProject.java:438)
20/08/2018 10:28:00	at org.geppetto.simulation.manager.GeppettoManager.runQueryCount(GeppettoManager.java:880)
20/08/2018 10:28:00	at org.geppetto.frontend.controllers.ConnectionHandler.runQueryCount(ConnectionHandler.java:495)
20/08/2018 10:28:00	at org.geppetto.frontend.controllers.WebsocketConnection.onTextMessage(WebsocketConnection.java:459)
20/08/2018 10:28:00	at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:78)
20/08/2018 10:28:00	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
20/08/2018 10:28:00	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
20/08/2018 10:28:00	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
20/08/2018 10:28:00	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:616)
20/08/2018 10:28:00	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
20/08/2018 10:28:00	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
20/08/2018 10:28:00	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
20/08/2018 10:28:00	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
20/08/2018 10:28:00	at java.lang.Thread.run(Thread.java:745)
20/08/2018 10:28:00
```

Failing here: https://github.com/VirtualFlyBrain/uk.ac.vfb.geppetto/blob/c753aad0e96198ecbb58c20aa3eff2f41f94e2d2/src/main/java/uk/ac/vfb/geppetto/NBLASTQueryProcessor.java#L57

**Comment by Robbie1977** [comment] 2018-08-20 14:08
The error was caused by NBLAST passing a result that doesn't exist (ATM) on VFB: 67A12 
I'm just pushing a fix that logs and skips such results.

**Comment by jefferis** [comment] 2018-08-20 14:09
Good catch, both. G.

**Comment by Robbie1977** [comment] 2018-08-20 17:13
Fixed on v2:
https://v2.virtualflybrain.org/?i=VFB_00017894,VFB_00003820

**Closed by Robbie1977** 2018-08-20 17:13 UTC
